name: Deploy FrontEnd

on:
  push:
    branches:
      - "master"
env:
  s3-bucket: demo-events-webapp

jobs:
  stage:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Check out
        uses: actions/checkout@v1
      - uses: actions/setup-node@v2

      #- name: Install Dependencies
      #  run: yarn install
      #- name: Build
      #  run: yarn build
      #- run: aws s3 rm s3://${{env.s3-bucket}}/  --recursive
      - name: Upload to S3
        run: |
          cd frontend
          yarn install
          yarn build
          aws s3 cp build  s3://${{env.s3-bucket}}/ --recursive
